<a href="https://colab.research.google.com/github/developerabhi14/ML-Notebooks/blob/main/Linear_Regression_using_Adam_Optimizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

In [57]:
X=np.array([200, 300,400,500,600,700,800,900,1000,1100])
Y=np.array([1000,1200,1300,1500,1750,1900,2100,2300,2500,2700])

In [58]:
X_mean, X_std = X.mean(), X.std()
X = (X - X_mean) / X_std  # Standardizing X
Y = Y / 1000  # Scale Y instead of standardizing

In [59]:
X, Y

(array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
         0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ]),
 array([1.  , 1.2 , 1.3 , 1.5 , 1.75, 1.9 , 2.1 , 2.3 , 2.5 , 2.7 ]))

In [60]:
X_tensor = torch.from_numpy(X).float().view(-1, 1)
Y_tensor = torch.from_numpy(Y).float().view(-1, 1)

In [61]:
X_tensor.shape, Y_tensor.shape

(torch.Size([10, 1]), torch.Size([10, 1]))

In [62]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, X):
        return self.linear(X)

    def loss_function(self, Y_pred, Y):
        mse_loss = nn.MSELoss()
        return mse_loss(Y_pred, Y)


In [70]:
epochs = 10000
learning_rate = 0.001
criterion = nn.MSELoss()

In [71]:
model = Model()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    y_pred = model(X_tensor)
    loss = criterion(y_pred, Y_tensor)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if(epoch%200==0):
      print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 7.405107021331787
Epoch: 201, Loss: 6.047852039337158
Epoch: 401, Loss: 4.903712272644043
Epoch: 601, Loss: 3.946653366088867
Epoch: 801, Loss: 3.1520471572875977
Epoch: 1001, Loss: 2.4971678256988525
Epoch: 1201, Loss: 1.9612150192260742
Epoch: 1401, Loss: 1.5254312753677368
Epoch: 1601, Loss: 1.1732546091079712
Epoch: 1801, Loss: 0.8904315829277039
Epoch: 2001, Loss: 0.6650069355964661
Epoch: 2201, Loss: 0.4871291518211365
Epoch: 2401, Loss: 0.34870103001594543
Epoch: 2601, Loss: 0.24295976758003235
Epoch: 2801, Loss: 0.1640959531068802
Epoch: 3001, Loss: 0.10697480291128159
Epoch: 3201, Loss: 0.06702889502048492
Epoch: 3401, Loss: 0.040215373039245605
Epoch: 3601, Loss: 0.0230450127273798
Epoch: 3801, Loss: 0.012627199292182922
Epoch: 4001, Loss: 0.006681270897388458
Epoch: 4201, Loss: 0.0035137427039444447
Epoch: 4401, Loss: 0.0019519098568707705
Epoch: 4601, Loss: 0.0012455424293875694
Epoch: 4801, Loss: 0.0009554304997436702
Epoch: 5001, Loss: 0.000848328403662890

In [74]:
# Function to make predictions
def predict(model, X_new):
    X_new = (X_new - X_mean) / X_std  # Apply the same normalization as training
    X_new_tensor = torch.tensor(X_new, dtype=torch.float32).view(-1, 1)
    Y_pred_scaled = model(X_new_tensor).detach().numpy()  # Get prediction
    Y_pred = Y_pred_scaled * 1000  # Reverse scaling
    return Y_pred

# Example: Predict prices for new areas
X_test = np.array([1200, 1300, 950, 1050])
predictions = predict(model, X_test)

print(predictions)

[[2869.998]
 [3059.998]
 [2394.998]
 [2584.998]]
