<a href="https://colab.research.google.com/github/developerabhi14/ML-Notebooks/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing numpy
import numpy as np

In [5]:
# Create array using python list
lists=[1,2,3,4]
print(lists)
print(type(lists))

print("\n")

# create a array from list
array1=np.array(lists)
print(array1)
print(type(array1))

[1, 2, 3, 4]
<class 'list'>


[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# We can also createa numpy array directly using a list
array1=np.array([1,2,3,4])
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
# Create an array using np.zeros()
array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [9]:
# Create array with np.arange()

# Creating array with values from 0 to 4
array1=np.arange(5)
print(array1)


[0 1 2 3 4]


In [10]:
# create an array with values from 1 to 8 with step of 2
array2=np.arange(1,9,2)
print(array2)

[1 3 5 7]


In [12]:
# Create an array with np.random.rand()

array1=np.random.rand(5)
print(array1)

[0.16320721 0.21092746 0.79971747 0.7859732  0.15832018]


In [13]:
# Create an empty array
array1=np.empty(4)
print(array1)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323]


# Python N-D array creation

In [14]:
# Create a 2D array with 2 rows and 4 columns

array1=np.array([[1,2,3,4],[5,6,7,8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# Create a 3D array with 3 rows and 4 columns with 2 slices
array1=np.array([[[1,2,3,4],
                   [5,6,7,8],
                  [9,10,11,12]],
                 [[13,14,15,16],
                  [17,18,19,20],
                  [21,22,23,24]]])
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
# Create N-D Arrays using np.zeros()

# create 2D array with 2 rows and 3 columns filled with zeros
array1 = np.zeros((2, 3))

print("2-D Array: ")
print(array1)

# create 3D array with dimensions 2x3x4 filled with zeros
array2 = np.zeros((2, 3, 4))

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0. 0. 0.]
 [0. 0. 0.]]

3-D Array: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
# Create N-D Array with a Specified Value

# Create a 2-D array with elements initialized to 5
numpy_array = np.full((2, 2), 5)

print("Array:", numpy_array)

Array: [[5 5]
 [5 5]]


In [18]:
# Creating Arrays With np.random.rand()

# create a 2D array of 2 rows and 2 columns of random numbers
array1 = np.random.rand(2, 2)


print("2-D Array: ")
print(array1)

# create a 3D array of shape (2, 2, 2) of random numbers
array2 = np.random.rand(2, 2, 2)


print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0.64647936 0.80604045]
 [0.2482399  0.33628917]]

3-D Array: 
[[[0.61937061 0.27020043]
  [0.12518898 0.14290313]]

 [[0.43935413 0.83388756]
  [0.40379773 0.67097859]]]


In [19]:
# Create Empty N-D NumPy Array

# create an empty 2D array with 2 rows and 2 columns
array1 = np.empty((2, 2))


print("2-D Array: ")
print(array1)

# create an empty 3D array of shape (2, 2, 2)
array2 = np.empty((2, 2, 2))


print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0.64647936 0.80604045]
 [0.2482399  0.33628917]]

3-D Array: 
[[[0.61937061 0.27020043]
  [0.12518898 0.14290313]]

 [[0.43935413 0.83388756]
  [0.40379773 0.67097859]]]


# Numpy Data Types

In [20]:
# Check Data Type of a NumPy Array

# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)


int64


In [21]:
# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)  # prints int64

# check the data type of float_array
print(float_array.dtype)  # prints float64

# check the data type of complex_array
print(complex_array.dtype)  # prints complex128

int64
float64
complex128


In [22]:
# Creating NumPy Arrays With a Defined Data Type

# create an array of 32-bit integers
array1 = np.array([1, 3, 7], dtype='int32')

print(array1, array1.dtype)

[1 3 7] int32


In [23]:
# create an array of 8-bit integers
array1 = np.array([1, 3, 7], dtype='int8')

# create an array of unsigned 16-bit integers
array2 = np.array([2, 4, 6], dtype='uint16')

# create an array of 32-bit floating-point numbers
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')

# create an array of 64-bit complex numbers
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

# print the arrays and their data types
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


In [24]:
# NumPy Type Conversion

# create an array of integers
int_array = np.array([1, 3, 5, 7])

# convert data type of int_array to float
float_array = int_array.astype('float')

# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64


# Access Array Elements Using Index

In [25]:
array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])    # prints 1
print(array1[2])    # prints 5
print(array1[4])    # prints 9


1
5
9


In [26]:
# Modify array elements using index

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10])

# change the value of the first element
numbers[0] = 12
print("After modifying first element:",numbers)    # prints [12 4 6 8 10]

# change the value of the third element
numbers[2] = 14
print("After modifying third element:",numbers)    # prints [12 4 14 8 10]

After modifying first element: [12  4  6  8 10]
After modifying third element: [12  4 14  8 10]


In [27]:
# NumPy Negative Array Indexing

# create a numpy array
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])    # prints 9

# access the second-to-last element
print(numbers[-2])    # prints 7

9
7


In [28]:
# Modify Array Elements Using Negative Indexing

# create a numpy array
numbers = np.array([2, 3, 5, 7, 11])

# modify the last element
numbers[-1] = 13
print(numbers)    # Output: [2 3 5 7 13]

# modify the second-to-last element
numbers[-2] = 17
print(numbers)

[ 2  3  5  7 13]
[ 2  3  5 17 13]


In [29]:
# 2-D NumPy Array Indexing

In [30]:
array1 = np.array([[1, 3, 5],
                     [7, 9, 2],
                     [4, 6, 8]])

array1[2, 1] # returns 6

np.int64(6)

In [31]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [32]:
# Access Row or Column of 2D Array Using Indexing

# create a 2D array
array1 = np.array([[1, 3, 5],
             [7, 9, 2],
             [4, 6, 8]])

# access the second row of the array
second_row = array1[1, :]
print("Second Row:", second_row)  # Output: [7 9 2]

# access the third column of the array
third_col = array1[:, 2]
print("Third Column:", third_col)  # Output: [5 2 8]

Second Row: [7 9 2]
Third Column: [5 2 8]


In [33]:
# 3-D NumPy Array Indexing

# create a 3D array with shape (2, 3, 4)
array1 = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],

                    [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

# access a specific element of the array
element = array1[1, 2, 1]

# print the value of the element
print(element)

22


# Numpy Array Slicing

In [34]:
# 1D NumPy Array Slicing

# create a 1D array
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


In [35]:
# Modify Array Elements Using Slicing

# 1. Using start parameter

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
numbers[3:] = 20
print(numbers)


[ 2  4  6 20 20 20]


In [36]:
# 2. Using stop parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify the first 3 elements
numbers[:3] = 40
print(numbers)


[40 40 40  8 10 12]


In [37]:
# 3. Using start and stop parameter

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from indices 2 to 5
numbers[2:5] = 22
print(numbers)

[ 2  4 22 22 22 12]


In [38]:
# 4. Using start, stop, and step parameter

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify every second element from indices 1 to 5
numbers[1:5:2] = 16
print(numbers)

[ 2 16  6 16 10 12]


In [39]:
# NumPy Array Negative Slicing

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print(numbers[-3:])    # [8 10 12]

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(numbers[-5:-2])    # [4 6 8]

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(numbers[-1::-2])   # [12 8 4]

[ 8 10 12]
[4 6 8]
[12  8  4]


In [40]:
# Reverse NumPy Array Using Negative Slicing

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# generate reversed array
reversed_numbers = numbers[::-1]
print(reversed_numbers)

[12 10  8  6  4  2]


In [41]:
# 2D NumPy Array Slicing

array1 = np.array([[1, 3, 5, 7],
                   [9, 11, 13, 15]])

print(array1[:2, :2])

[[ 1  3]
 [ 9 11]]


In [42]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]
